
package ec.edu.ups.est.ProyectoFinal;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:11:50.203-05:00
 * Generated source version: 3.5.0
 *
 */
public class AutomovilSOAP_AutomovilSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://bean.ProyectoFinal.est.ups.edu.ec/", "AutomovilSOAPService");

    private AutomovilSOAP_AutomovilSOAPPort_Client() {
    }

    
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AutomovilSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AutomovilSOAPService ss = new AutomovilSOAPService(wsdlURL, SERVICE_NAME);
        AutomovilSOAP port = ss.getAutomovilSOAPPort();

        {
        System.out.println("Invoking crearAutomovil...");
        java.lang.String _crearAutomovil_arg0 = "";
        java.lang.String _crearAutomovil_arg1 = "";
        java.lang.String _crearAutomovil_arg2 = "";
        java.lang.String _crearAutomovil_arg3 = "";
        java.lang.String _crearAutomovil__return = port.crearAutomovil(_crearAutomovil_arg0, _crearAutomovil_arg1, _crearAutomovil_arg2, _crearAutomovil_arg3);
        System.out.println("crearAutomovil.result=" + _crearAutomovil__return);


        }
        {
        System.out.println("Invoking getAutomoviles...");
        java.util.List<ec.edu.ups.est.ProyectoFinal.Automovil> _getAutomoviles__return = port.getAutomoviles();
        System.out.println("getAutomoviles.result=" + _getAutomoviles__return);


        }

        System.exit(0);
    }
    
    public void insertarVehiculo(String placa, String marca, String modelo, String color) {
    	URL wsdlURL = AutomovilSOAPService.WSDL_LOCATION;

        AutomovilSOAPService ss = new AutomovilSOAPService(wsdlURL, SERVICE_NAME);
        AutomovilSOAP port = ss.getAutomovilSOAPPort();
        
        port.crearAutomovil(placa, marca, modelo, color);
        
    }

}
