package ec.edu.ups.est.ProyectoFinal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:11:50.366-05:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "AutomovilSOAPService",
                  wsdlLocation = "http://localhost:8080/ProyectoFinal/AutomovilSOAP?wsdl",
                  targetNamespace = "http://bean.ProyectoFinal.est.ups.edu.ec/")
public class AutomovilSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bean.ProyectoFinal.est.ups.edu.ec/", "AutomovilSOAPService");
    public final static QName AutomovilSOAPPort = new QName("http://bean.ProyectoFinal.est.ups.edu.ec/", "AutomovilSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ProyectoFinal/AutomovilSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutomovilSOAPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ProyectoFinal/AutomovilSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AutomovilSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutomovilSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutomovilSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AutomovilSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AutomovilSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AutomovilSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AutomovilSOAP
     */
    @WebEndpoint(name = "AutomovilSOAPPort")
    public AutomovilSOAP getAutomovilSOAPPort() {
        return super.getPort(AutomovilSOAPPort, AutomovilSOAP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutomovilSOAP
     */
    @WebEndpoint(name = "AutomovilSOAPPort")
    public AutomovilSOAP getAutomovilSOAPPort(WebServiceFeature... features) {
        return super.getPort(AutomovilSOAPPort, AutomovilSOAP.class, features);
    }

}
