package ec.edu.ups.est.ProyectoFinal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:11:50.352-05:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://bean.ProyectoFinal.est.ups.edu.ec/", name = "AutomovilSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface AutomovilSOAP {

    @WebMethod
    @RequestWrapper(localName = "crearAutomovil", targetNamespace = "http://bean.ProyectoFinal.est.ups.edu.ec/", className = "ec.edu.ups.est.ProyectoFinal.CrearAutomovil")
    @ResponseWrapper(localName = "crearAutomovilResponse", targetNamespace = "http://bean.ProyectoFinal.est.ups.edu.ec/", className = "ec.edu.ups.est.ProyectoFinal.CrearAutomovilResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearAutomovil(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "getAutomoviles", targetNamespace = "http://bean.ProyectoFinal.est.ups.edu.ec/", className = "ec.edu.ups.est.ProyectoFinal.GetAutomoviles")
    @ResponseWrapper(localName = "getAutomovilesResponse", targetNamespace = "http://bean.ProyectoFinal.est.ups.edu.ec/", className = "ec.edu.ups.est.ProyectoFinal.GetAutomovilesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.est.ProyectoFinal.Automovil> getAutomoviles()
;
}
